## Even Fibonacci numbers
##
## Each new term in the Fibonacci sequence is generated by adding
## the previous two terms. By starting with 1 and 2, the first 10
## terms will be:
##
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
## By considering the terms in the Fibonacci sequence whose values
## do not exceed four million, find the sum of the even-valued terms.
##
## ans: 4613732


iterator fib(): int =
    var a = 1
    var b = 1

    while true:
        yield a
        b = a + b
        yield b
        a = a + b

proc ans(limit: int): int =
    var sum: int
    for i in fib():
        if i > limit:
            break

        if i mod 2 == 0:
            sum.inc(i)

    return sum

echo ans 4_000_000
